version: '2.4'

services:
  quiz:
    container_name: quiz
    build: .
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      - "PRIZE=here is your prize!"
    pids_limit: 256
    mem_limit: 256M
    cpus: 1
